// Exercise library — sourced from training knowledge of standard S&C progressions.
// Review difficulty ratings and progression chains before trusting AI coach output.

export type MovementPattern =
  | 'hinge'
  | 'squat'
  | 'push_horizontal'
  | 'push_vertical'
  | 'pull_horizontal'
  | 'pull_vertical'
  | 'hip_extension'
  | 'hamstring'
  | 'core'
  | 'conditioning'
  | 'accessory';

export type Equipment =
  | 'bodyweight'
  | 'barbell'
  | 'dumbbell'
  | 'cable'
  | 'machine'
  | 'band'
  | 'kettlebell'
  | 'rower'
  | 'assault_bike'
  | 'battle_rope'
  | 'box';

export interface ExerciseEntry {
  id: string;
  name: string;
  pattern: MovementPattern;
  muscles: string[];
  equipment: Equipment[];
  // 1 = complete beginner, 5 = advanced
  difficulty: 1 | 2 | 3 | 4 | 5;
  progressions: string[];  // IDs of harder variations
  regressions: string[];   // IDs of easier variations
  notes?: string;
}

export const exercises: ExerciseEntry[] = [

  // ─── HINGE ────────────────────────────────────────────────────────────────

  {
    id: 'cable_pull_through',
    name: 'Cable Pull-Through',
    pattern: 'hinge',
    muscles: ['glutes', 'hamstrings', 'lower back'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: ['db_rdl', 'trap_bar_deadlift'],
    regressions: [],
    notes: 'Best intro to the hip hinge pattern. Focus on pushing hips back, not bending knees.',
  },
  {
    id: 'db_rdl',
    name: 'DB Romanian Deadlift',
    pattern: 'hinge',
    muscles: ['hamstrings', 'glutes', 'lower back'],
    equipment: ['dumbbell'],
    difficulty: 1,
    progressions: ['bb_rdl', 'db_single_leg_rdl'],
    regressions: ['cable_pull_through'],
  },
  {
    id: 'bb_rdl',
    name: 'Romanian Deadlift',
    pattern: 'hinge',
    muscles: ['hamstrings', 'glutes', 'lower back'],
    equipment: ['barbell'],
    difficulty: 2,
    progressions: ['bb_conventional_deadlift', 'bb_stiff_leg_deadlift'],
    regressions: ['db_rdl'],
    notes: 'Keep bar close to legs, soft knee bend, hinge until you feel a stretch in the hamstrings.',
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Trap Bar Deadlift',
    pattern: 'hinge',
    muscles: ['glutes', 'hamstrings', 'quads', 'lower back'],
    equipment: ['barbell'],
    difficulty: 2,
    progressions: ['bb_conventional_deadlift'],
    regressions: ['db_rdl'],
    notes: 'More forgiving on the lower back than conventional. Good stepping stone to barbell deadlift.',
  },
  {
    id: 'bb_conventional_deadlift',
    name: 'Conventional Deadlift',
    pattern: 'hinge',
    muscles: ['glutes', 'hamstrings', 'lower back', 'traps', 'lats'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: ['bb_sumo_deadlift', 'bb_deficit_deadlift'],
    regressions: ['bb_rdl', 'trap_bar_deadlift'],
    notes: 'Brace hard before lifting. Bar stays over mid-foot throughout.',
  },
  {
    id: 'bb_sumo_deadlift',
    name: 'Sumo Deadlift',
    pattern: 'hinge',
    muscles: ['glutes', 'hamstrings', 'quads', 'adductors', 'lower back'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: ['bb_deficit_deadlift'],
    regressions: ['bb_conventional_deadlift'],
    notes: 'Wide stance, toes out. More glute and adductor dominant than conventional.',
  },
  {
    id: 'db_single_leg_rdl',
    name: 'Single-Leg RDL',
    pattern: 'hinge',
    muscles: ['hamstrings', 'glutes', 'lower back'],
    equipment: ['dumbbell'],
    difficulty: 3,
    progressions: ['bb_single_leg_rdl'],
    regressions: ['db_rdl'],
    notes: 'Challenges balance and hip stability. Hold DB in opposite hand to working leg.',
  },
  {
    id: 'bb_single_leg_rdl',
    name: 'Single-Leg RDL (Barbell)',
    pattern: 'hinge',
    muscles: ['hamstrings', 'glutes', 'lower back'],
    equipment: ['barbell'],
    difficulty: 4,
    progressions: [],
    regressions: ['db_single_leg_rdl'],
  },
  {
    id: 'bb_deficit_deadlift',
    name: 'Deficit Deadlift',
    pattern: 'hinge',
    muscles: ['glutes', 'hamstrings', 'lower back', 'quads'],
    equipment: ['barbell'],
    difficulty: 4,
    progressions: [],
    regressions: ['bb_conventional_deadlift'],
    notes: 'Stand on a 1–2 inch plate. Increases range of motion and quad demand.',
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    pattern: 'hinge',
    muscles: ['hamstrings', 'lower back', 'glutes'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: [],
    regressions: ['bb_rdl'],
    notes: 'Bar on upper back, hinge at the hips. Use light weight — it loads the lower back heavily.',
  },

  // ─── SQUAT ────────────────────────────────────────────────────────────────

  {
    id: 'leg_press',
    name: 'Leg Press',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 1,
    progressions: ['db_goblet_squat', 'hack_squat_machine'],
    regressions: [],
    notes: 'Good for building quad confidence before barbell squats. Do not lock knees at top.',
  },
  {
    id: 'db_goblet_squat',
    name: 'DB Goblet Squat',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'core'],
    equipment: ['dumbbell'],
    difficulty: 1,
    progressions: ['box_squat', 'hack_squat_machine'],
    regressions: ['leg_press'],
    notes: 'Hold DB vertically at chest. Elbows inside knees at the bottom.',
  },
  {
    id: 'step_up_bw',
    name: 'Step-up',
    pattern: 'squat',
    muscles: ['quads', 'glutes'],
    equipment: ['bodyweight', 'box'],
    difficulty: 1,
    progressions: ['step_up_db', 'reverse_lunge_bw'],
    regressions: [],
  },
  {
    id: 'reverse_lunge_bw',
    name: 'Reverse Lunge',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 1,
    progressions: ['reverse_lunge_db', 'bulgarian_split_squat_bw'],
    regressions: ['step_up_bw'],
    notes: 'Step back, not forward. More knee-friendly than forward lunge.',
  },
  {
    id: 'step_up_db',
    name: 'Step-up (Dumbbell)',
    pattern: 'squat',
    muscles: ['quads', 'glutes'],
    equipment: ['dumbbell', 'box'],
    difficulty: 2,
    progressions: ['bulgarian_split_squat_db'],
    regressions: ['step_up_bw'],
  },
  {
    id: 'box_squat',
    name: 'Box Squat',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['barbell', 'box'],
    difficulty: 2,
    progressions: ['bb_back_squat'],
    regressions: ['db_goblet_squat'],
    notes: 'Sit back onto box, pause briefly, drive up. Teaches proper squat depth and hip-back mechanics.',
  },
  {
    id: 'hack_squat_machine',
    name: 'Hack Squat',
    pattern: 'squat',
    muscles: ['quads', 'glutes'],
    equipment: ['machine'],
    difficulty: 2,
    progressions: ['bb_back_squat', 'bb_front_squat'],
    regressions: ['leg_press', 'db_goblet_squat'],
  },
  {
    id: 'reverse_lunge_db',
    name: 'Reverse Lunge (Dumbbell)',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['bulgarian_split_squat_db'],
    regressions: ['reverse_lunge_bw'],
  },
  {
    id: 'bulgarian_split_squat_bw',
    name: 'Bulgarian Split Squat',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['bulgarian_split_squat_db'],
    regressions: ['reverse_lunge_bw'],
    notes: 'Rear foot elevated on bench. Front foot far enough forward that shin stays vertical.',
  },
  {
    id: 'bulgarian_split_squat_db',
    name: 'Bulgarian Split Squat (Dumbbell)',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['dumbbell'],
    difficulty: 3,
    progressions: ['bulgarian_split_squat_bb'],
    regressions: ['bulgarian_split_squat_bw'],
  },
  {
    id: 'bb_back_squat',
    name: 'Back Squat',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: ['bb_pause_squat', 'bb_front_squat'],
    regressions: ['box_squat', 'hack_squat_machine'],
    notes: 'Brace core before descent. Knees track over toes. Break parallel.',
  },
  {
    id: 'bulgarian_split_squat_bb',
    name: 'Bulgarian Split Squat (Barbell)',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings'],
    equipment: ['barbell'],
    difficulty: 4,
    progressions: [],
    regressions: ['bulgarian_split_squat_db'],
  },
  {
    id: 'bb_pause_squat',
    name: 'Pause Squat',
    pattern: 'squat',
    muscles: ['quads', 'glutes', 'hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 4,
    progressions: [],
    regressions: ['bb_back_squat'],
    notes: '2–3 second pause at the bottom. Eliminates stretch reflex, builds raw strength out of the hole.',
  },
  {
    id: 'bb_front_squat',
    name: 'Front Squat',
    pattern: 'squat',
    muscles: ['quads', 'core', 'upper back'],
    equipment: ['barbell'],
    difficulty: 4,
    progressions: [],
    regressions: ['bb_back_squat', 'hack_squat_machine'],
    notes: 'More upright torso and quad-dominant than back squat. Demanding on wrist and thoracic mobility.',
  },

  // ─── PUSH — HORIZONTAL ────────────────────────────────────────────────────

  {
    id: 'incline_pushup',
    name: 'Incline Push-up',
    pattern: 'push_horizontal',
    muscles: ['chest', 'triceps', 'front delts'],
    equipment: ['bodyweight'],
    difficulty: 1,
    progressions: ['pushup'],
    regressions: [],
    notes: 'Hands on a bench or wall. Easier than floor push-up — good starting point.',
  },
  {
    id: 'pushup',
    name: 'Push-up',
    pattern: 'push_horizontal',
    muscles: ['chest', 'triceps', 'front delts', 'core'],
    equipment: ['bodyweight'],
    difficulty: 1,
    progressions: ['archer_pushup', 'db_bench_press'],
    regressions: ['incline_pushup'],
    notes: 'Body in a straight line. Elbows at ~45° from torso, not flared wide.',
  },
  {
    id: 'db_bench_press',
    name: 'DB Bench Press',
    pattern: 'push_horizontal',
    muscles: ['chest', 'triceps', 'front delts'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['bb_bench_press', 'incline_db_press'],
    regressions: ['pushup'],
    notes: 'Greater range of motion than barbell. Each arm works independently.',
  },
  {
    id: 'incline_db_press',
    name: 'Incline DB Press',
    pattern: 'push_horizontal',
    muscles: ['upper chest', 'triceps', 'front delts'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['incline_bb_press'],
    regressions: ['db_bench_press'],
  },
  {
    id: 'cable_chest_fly',
    name: 'Cable Chest Fly',
    pattern: 'push_horizontal',
    muscles: ['chest'],
    equipment: ['cable'],
    difficulty: 2,
    progressions: [],
    regressions: ['db_bench_press'],
    notes: 'Isolation movement. Keeps tension on the chest through the full range.',
  },
  {
    id: 'archer_pushup',
    name: 'Archer Push-up',
    pattern: 'push_horizontal',
    muscles: ['chest', 'triceps', 'front delts'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: [],
    regressions: ['pushup'],
    notes: 'One arm does most of the work while the other extends out. Builds toward one-arm push-up.',
  },
  {
    id: 'bb_bench_press',
    name: 'Barbell Bench Press',
    pattern: 'push_horizontal',
    muscles: ['chest', 'triceps', 'front delts'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: ['incline_bb_press'],
    regressions: ['db_bench_press'],
    notes: 'Retract scapula before lowering. Touch chest, drive bar back up in a slight arc.',
  },
  {
    id: 'incline_bb_press',
    name: 'Incline Barbell Press',
    pattern: 'push_horizontal',
    muscles: ['upper chest', 'triceps', 'front delts'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: [],
    regressions: ['incline_db_press'],
  },
  {
    id: 'dips',
    name: 'Dips',
    pattern: 'push_horizontal',
    muscles: ['chest', 'triceps', 'front delts'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: [],
    regressions: ['pushup', 'db_bench_press'],
    notes: 'Lean forward slightly for chest emphasis. Stay upright for tricep emphasis.',
  },

  // ─── PUSH — VERTICAL ──────────────────────────────────────────────────────

  {
    id: 'lateral_raise_db',
    name: 'Lateral Raise',
    pattern: 'push_vertical',
    muscles: ['side delts'],
    equipment: ['dumbbell'],
    difficulty: 1,
    progressions: ['lateral_raise_cable'],
    regressions: [],
    notes: 'Slight forward lean, lead with elbows. Stop at shoulder height.',
  },
  {
    id: 'lateral_raise_cable',
    name: 'Cable Lateral Raise',
    pattern: 'push_vertical',
    muscles: ['side delts'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: [],
    regressions: ['lateral_raise_db'],
    notes: 'Cable keeps tension at the bottom unlike dumbbells. Use low pulley.',
  },
  {
    id: 'pike_pushup',
    name: 'Pike Push-up',
    pattern: 'push_vertical',
    muscles: ['front delts', 'triceps', 'upper chest'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['db_shoulder_press'],
    regressions: ['pushup'],
    notes: 'Hips high, head goes toward floor between hands. Vertical press pattern with bodyweight.',
  },
  {
    id: 'db_shoulder_press',
    name: 'DB Shoulder Press',
    pattern: 'push_vertical',
    muscles: ['front delts', 'side delts', 'triceps'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['bb_overhead_press'],
    regressions: ['pike_pushup'],
    notes: 'Seated or standing. Keep core braced — avoid arching lower back.',
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    pattern: 'push_vertical',
    muscles: ['front delts', 'side delts', 'triceps'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['bb_overhead_press'],
    regressions: ['db_shoulder_press'],
    notes: 'Start with palms facing you, rotate as you press. Hits more of the delt than standard press.',
  },
  {
    id: 'bb_overhead_press',
    name: 'Overhead Press',
    pattern: 'push_vertical',
    muscles: ['front delts', 'side delts', 'triceps', 'upper traps'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: [],
    regressions: ['db_shoulder_press'],
    notes: 'Bar starts at upper chest. Press straight up, shrug at the top. Brace hard.',
  },

  // ─── PULL — HORIZONTAL ────────────────────────────────────────────────────

  {
    id: 'band_face_pull',
    name: 'Band Face Pull',
    pattern: 'pull_horizontal',
    muscles: ['rear delts', 'external rotators', 'mid traps'],
    equipment: ['band'],
    difficulty: 1,
    progressions: ['cable_face_pull'],
    regressions: [],
    notes: 'Pull to face, elbows high and wide. Essential for shoulder health.',
  },
  {
    id: 'cable_face_pull',
    name: 'Cable Face Pull',
    pattern: 'pull_horizontal',
    muscles: ['rear delts', 'external rotators', 'mid traps'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: [],
    regressions: ['band_face_pull'],
    notes: 'Use rope attachment at face height. Elbows above wrists at the end position.',
  },
  {
    id: 'cable_row',
    name: 'Seated Cable Row',
    pattern: 'pull_horizontal',
    muscles: ['lats', 'mid traps', 'biceps', 'rear delts'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: ['db_bent_over_row', 'chest_supported_db_row'],
    regressions: [],
    notes: 'Drive elbows back, not up. Squeeze shoulder blades at the end.',
  },
  {
    id: 'chest_supported_db_row',
    name: 'Chest-Supported DB Row',
    pattern: 'pull_horizontal',
    muscles: ['lats', 'mid traps', 'rear delts', 'biceps'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['db_bent_over_row'],
    regressions: ['cable_row'],
    notes: 'Chest on incline bench — removes lower back from the equation entirely.',
  },
  {
    id: 'db_bent_over_row',
    name: 'DB Bent-Over Row',
    pattern: 'pull_horizontal',
    muscles: ['lats', 'mid traps', 'rear delts', 'biceps'],
    equipment: ['dumbbell'],
    difficulty: 2,
    progressions: ['bb_bent_over_row'],
    regressions: ['cable_row', 'chest_supported_db_row'],
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    pattern: 'pull_horizontal',
    muscles: ['lats', 'mid traps', 'rear delts', 'biceps'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['pullup'],
    regressions: ['cable_row'],
    notes: 'Body straight, pull chest to bar. Harder the more horizontal your body is.',
  },
  {
    id: 'bb_bent_over_row',
    name: 'Barbell Bent-Over Row',
    pattern: 'pull_horizontal',
    muscles: ['lats', 'mid traps', 'lower back', 'biceps'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: [],
    regressions: ['db_bent_over_row'],
    notes: 'Hinge to ~45°, brace hard. Row to lower chest, not upper.',
  },

  // ─── PULL — VERTICAL ──────────────────────────────────────────────────────

  {
    id: 'straight_arm_pulldown',
    name: 'Straight Arm Pulldown',
    pattern: 'pull_vertical',
    muscles: ['lats', 'teres major'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: ['lat_pulldown'],
    regressions: [],
    notes: 'Isolates the lat without bicep involvement. Good for learning to feel the lat.',
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    pattern: 'pull_vertical',
    muscles: ['lats', 'biceps', 'rear delts'],
    equipment: ['machine'],
    difficulty: 1,
    progressions: ['assisted_pullup', 'pullup'],
    regressions: ['straight_arm_pulldown'],
    notes: 'Pull to upper chest, not behind the neck. Slight lean back is fine.',
  },
  {
    id: 'assisted_pullup',
    name: 'Assisted Pull-up',
    pattern: 'pull_vertical',
    muscles: ['lats', 'biceps', 'rear delts'],
    equipment: ['machine'],
    difficulty: 2,
    progressions: ['pullup', 'chinup'],
    regressions: ['lat_pulldown'],
    notes: 'Use machine or band. Gradually reduce assistance over weeks.',
  },
  {
    id: 'chinup',
    name: 'Chin-up',
    pattern: 'pull_vertical',
    muscles: ['lats', 'biceps', 'rear delts'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: ['pullup', 'weighted_pullup'],
    regressions: ['assisted_pullup', 'lat_pulldown'],
    notes: 'Supinated grip (palms facing you). More bicep involvement than pull-up.',
  },
  {
    id: 'pullup',
    name: 'Pull-up',
    pattern: 'pull_vertical',
    muscles: ['lats', 'biceps', 'rear delts', 'core'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: ['weighted_pullup'],
    regressions: ['assisted_pullup', 'chinup'],
    notes: 'Pronated grip. Full hang at the bottom, chin over bar at the top.',
  },
  {
    id: 'neutral_grip_pullup',
    name: 'Neutral Grip Pull-up',
    pattern: 'pull_vertical',
    muscles: ['lats', 'biceps', 'rear delts'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: ['weighted_pullup'],
    regressions: ['assisted_pullup'],
    notes: 'Palms facing each other. Generally easier on the shoulder than pronated grip.',
  },
  {
    id: 'weighted_pullup',
    name: 'Weighted Pull-up',
    pattern: 'pull_vertical',
    muscles: ['lats', 'biceps', 'rear delts', 'core'],
    equipment: ['bodyweight'],
    difficulty: 4,
    progressions: [],
    regressions: ['pullup'],
    notes: 'Use a belt or hold a DB between feet.',
  },

  // ─── HIP EXTENSION ────────────────────────────────────────────────────────

  {
    id: 'glute_bridge_bw',
    name: 'Glute Bridge',
    pattern: 'hip_extension',
    muscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 1,
    progressions: ['bb_hip_thrust', 'single_leg_glute_bridge'],
    regressions: [],
    notes: 'Squeeze glutes hard at the top. Do not hyperextend the lower back.',
  },
  {
    id: 'cable_kickback',
    name: 'Cable Kickback',
    pattern: 'hip_extension',
    muscles: ['glutes'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: [],
    regressions: [],
    notes: 'Isolation movement. Keep hips level, move only at the hip joint.',
  },
  {
    id: 'single_leg_glute_bridge',
    name: 'Single-Leg Glute Bridge',
    pattern: 'hip_extension',
    muscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['single_leg_hip_thrust'],
    regressions: ['glute_bridge_bw'],
  },
  {
    id: 'bb_hip_thrust',
    name: 'Hip Thrust',
    pattern: 'hip_extension',
    muscles: ['glutes', 'hamstrings'],
    equipment: ['barbell'],
    difficulty: 2,
    progressions: ['single_leg_hip_thrust'],
    regressions: ['glute_bridge_bw'],
    notes: 'Upper back on bench, bar padded across hips. Drive through heels, full hip extension at top.',
  },
  {
    id: 'machine_hip_thrust',
    name: 'Hip Thrust (Machine)',
    pattern: 'hip_extension',
    muscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    difficulty: 2,
    progressions: ['bb_hip_thrust'],
    regressions: ['glute_bridge_bw'],
  },
  {
    id: 'single_leg_hip_thrust',
    name: 'Single-Leg Hip Thrust',
    pattern: 'hip_extension',
    muscles: ['glutes', 'hamstrings'],
    equipment: ['barbell'],
    difficulty: 3,
    progressions: [],
    regressions: ['bb_hip_thrust', 'single_leg_glute_bridge'],
  },

  // ─── HAMSTRING ISOLATION ──────────────────────────────────────────────────

  {
    id: 'leg_curl_machine',
    name: 'Leg Curl',
    pattern: 'hamstring',
    muscles: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 1,
    progressions: ['single_leg_leg_curl'],
    regressions: [],
  },
  {
    id: 'single_leg_leg_curl',
    name: 'Single-Leg Leg Curl',
    pattern: 'hamstring',
    muscles: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 2,
    progressions: ['nordic_curl'],
    regressions: ['leg_curl_machine'],
    notes: 'Exposes side-to-side imbalances.',
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Curl',
    pattern: 'hamstring',
    muscles: ['hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 4,
    progressions: [],
    regressions: ['single_leg_leg_curl'],
    notes: 'Eccentric-dominant. Kneel with feet anchored, slowly lower torso. One of the most effective hamstring exercises.',
  },

  // ─── CORE ─────────────────────────────────────────────────────────────────

  {
    id: 'plank',
    name: 'Plank',
    pattern: 'core',
    muscles: ['core', 'shoulders', 'glutes'],
    equipment: ['bodyweight'],
    difficulty: 1,
    progressions: ['side_plank', 'dead_bug', 'hollow_body_hold'],
    regressions: [],
    notes: 'Squeeze everything — glutes, abs, quads. Do not let hips sag or pike.',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    pattern: 'core',
    muscles: ['core', 'hip flexors'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['hollow_body_hold'],
    regressions: ['plank'],
    notes: 'Lower back pressed flat into floor throughout. Extend opposite arm/leg, never let back lift.',
  },
  {
    id: 'side_plank',
    name: 'Side Plank',
    pattern: 'core',
    muscles: ['obliques', 'glutes', 'core'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['copenhagen_plank'],
    regressions: ['plank'],
  },
  {
    id: 'russian_twist',
    name: 'Russian Twist',
    pattern: 'core',
    muscles: ['obliques', 'core'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: [],
    regressions: ['plank'],
    notes: 'Feet off floor, rotate side to side. Add a plate once bodyweight is easy.',
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    pattern: 'core',
    muscles: ['obliques', 'core'],
    equipment: ['cable'],
    difficulty: 2,
    progressions: [],
    regressions: ['plank'],
    notes: 'Anti-rotation core exercise. Resist the cable pulling you sideways. Hold at full extension.',
  },
  {
    id: 'cable_crunch',
    name: 'Cable Crunch',
    pattern: 'core',
    muscles: ['rectus abdominis'],
    equipment: ['cable'],
    difficulty: 2,
    progressions: ['hanging_leg_raise'],
    regressions: ['plank'],
    notes: 'Kneel facing cable. Flex spine — pull ribcage to pelvis, not head to knees.',
  },
  {
    id: 'hanging_knee_raise',
    name: 'Hanging Knee Raise',
    pattern: 'core',
    muscles: ['hip flexors', 'core'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['hanging_leg_raise'],
    regressions: ['dead_bug'],
  },
  {
    id: 'hollow_body_hold',
    name: 'Hollow Body Hold',
    pattern: 'core',
    muscles: ['core', 'hip flexors'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: ['ab_wheel_rollout'],
    regressions: ['dead_bug', 'plank'],
    notes: 'Lower back pressed flat, arms and legs just off floor. The foundation of gymnastics strength.',
  },
  {
    id: 'copenhagen_plank',
    name: 'Copenhagen Plank',
    pattern: 'core',
    muscles: ['adductors', 'obliques', 'core'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: [],
    regressions: ['side_plank'],
    notes: 'Top foot on bench in side plank position. Brutal on the adductors.',
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    pattern: 'core',
    muscles: ['core', 'hip flexors'],
    equipment: ['bodyweight'],
    difficulty: 3,
    progressions: ['ab_wheel_rollout'],
    regressions: ['hanging_knee_raise'],
    notes: 'Legs straight. Tilt pelvis at the top — do not just swing the legs.',
  },
  {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    pattern: 'core',
    muscles: ['core', 'lats', 'shoulders'],
    equipment: ['bodyweight'],
    difficulty: 4,
    progressions: [],
    regressions: ['hollow_body_hold', 'plank'],
    notes: 'Start with partial range from knees. One of the best anti-extension core exercises.',
  },

  // ─── CONDITIONING ─────────────────────────────────────────────────────────

  {
    id: 'rowing_machine',
    name: 'Rowing Machine',
    pattern: 'conditioning',
    muscles: ['full body'],
    equipment: ['rower'],
    difficulty: 2,
    progressions: [],
    regressions: [],
    notes: 'Drive with legs first (60%), then hips (20%), then arms (20%). Drag factor 110–130.',
  },
  {
    id: 'assault_bike',
    name: 'Assault Bike',
    pattern: 'conditioning',
    muscles: ['full body'],
    equipment: ['assault_bike'],
    difficulty: 2,
    progressions: [],
    regressions: [],
    notes: 'Full body cardio. Push and pull the handles — do not just pedal.',
  },
  {
    id: 'battle_rope_slams',
    name: 'Battle Rope Slams',
    pattern: 'conditioning',
    muscles: ['shoulders', 'core', 'lats'],
    equipment: ['battle_rope'],
    difficulty: 2,
    progressions: [],
    regressions: [],
    notes: 'Drive from the hips and core, not just the arms. Max power per slam.',
  },
  {
    id: 'box_jump',
    name: 'Box Jump',
    pattern: 'conditioning',
    muscles: ['quads', 'glutes', 'calves'],
    equipment: ['box'],
    difficulty: 3,
    progressions: [],
    regressions: ['step_up_bw'],
    notes: 'Land softly with knees bent. Step down — do not jump down.',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    pattern: 'conditioning',
    muscles: ['full body'],
    equipment: ['bodyweight'],
    difficulty: 2,
    progressions: ['box_jump'],
    regressions: [],
  },

  // ─── ACCESSORY ────────────────────────────────────────────────────────────

  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    pattern: 'accessory',
    muscles: ['triceps'],
    equipment: ['cable'],
    difficulty: 1,
    progressions: ['overhead_tricep_extension'],
    regressions: [],
    notes: 'Elbows pinned to sides. Full extension at the bottom.',
  },
  {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    pattern: 'accessory',
    muscles: ['triceps'],
    equipment: ['cable', 'dumbbell'],
    difficulty: 1,
    progressions: [],
    regressions: ['tricep_pushdown'],
    notes: 'Stretches the long head. Cable version has better resistance curve.',
  },
  {
    id: 'db_bicep_curl',
    name: 'Bicep Curl',
    pattern: 'accessory',
    muscles: ['biceps'],
    equipment: ['dumbbell'],
    difficulty: 1,
    progressions: ['hammer_curl'],
    regressions: [],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    pattern: 'accessory',
    muscles: ['biceps', 'brachialis', 'brachioradialis'],
    equipment: ['dumbbell'],
    difficulty: 1,
    progressions: [],
    regressions: ['db_bicep_curl'],
    notes: 'Neutral grip. Hits brachialis and brachioradialis more than standard curl.',
  },
  {
    id: 'band_pull_apart',
    name: 'Band Pull-Apart',
    pattern: 'accessory',
    muscles: ['rear delts', 'mid traps', 'external rotators'],
    equipment: ['band'],
    difficulty: 1,
    progressions: ['band_face_pull'],
    regressions: [],
    notes: 'Squeeze shoulder blades together at the end. Essential for shoulder health.',
  },
  {
    id: 'calf_raise_machine',
    name: 'Calf Raise',
    pattern: 'accessory',
    muscles: ['gastrocnemius', 'soleus'],
    equipment: ['machine'],
    difficulty: 1,
    progressions: [],
    regressions: [],
    notes: 'Full range — stretch at the bottom, hard squeeze at the top. Slow and controlled beats heavy and bouncy.',
  },
  {
    id: 'leg_extension_machine',
    name: 'Leg Extension',
    pattern: 'accessory',
    muscles: ['quads'],
    equipment: ['machine'],
    difficulty: 1,
    progressions: [],
    regressions: [],
    notes: 'Isolation for the quads. Use as a finisher, not a main movement.',
  },
  {
    id: 'band_walk',
    name: 'Band Walk',
    pattern: 'accessory',
    muscles: ['glutes', 'abductors'],
    equipment: ['band'],
    difficulty: 1,
    progressions: [],
    regressions: [],
    notes: 'Band around ankles or just above knees. Stay in a quarter-squat throughout.',
  },
];

// Helper: get all exercises for a given movement pattern
export function getByPattern(pattern: MovementPattern): ExerciseEntry[] {
  return exercises.filter(e => e.pattern === pattern);
}

// Helper: get an exercise by ID
export function getById(id: string): ExerciseEntry | undefined {
  return exercises.find(e => e.id === id);
}

// Helper: get exercises at or below a given difficulty
export function getByMaxDifficulty(max: number): ExerciseEntry[] {
  return exercises.filter(e => e.difficulty <= max);
}

// Helper: get exercises that require only specific equipment
export function getByEquipment(available: Equipment[]): ExerciseEntry[] {
  return exercises.filter(e => e.equipment.every(eq => available.includes(eq)));
}
